Possible missing peer dependencies
valtech-ch/eslint-config pull request #1
Opened 2021-03-26 13:35 UTC by sanoodles

2021-03-26 13:39 UTC, sanoodles commented
I underline the commit message:

> Fixes error 'ESLint couldn't find the config react-app to extend from.' when running 'npx eslint src --ext .js' on a fresh 'npx create-react-app foo' application.

Though I wonder how this works with non-react applications. Will it also be added to it? I can try it now actually.

2021-03-26 14:39 UTC, sanoodles commented
OK for non-react apps the devDependencies are also added. But only the right ones will kick in if you set the right ones in .eslintrc.json. Seems alright.

2021-03-29 14:42 UTC, lorenzogm requested changes

2021-03-29 14:42 UTC, lorenzogm commented on README.md
> +For React applications, the corresponding documentation is at [Creating a TypeScript App](https://create-react-app.dev/docs/getting-started#creating-a-typescript-app).
I think this is not relevant for this package, we should remove this line.

2021-03-29 14:57 UTC, sanoodles commented on README.md
> +For React applications, the corresponding documentation is at [Creating a TypeScript App](https://create-react-app.dev/docs/getting-started#creating-a-typescript-app).
Yeah it is arguable at best. The thought was "since you want our linting, know that it requires typescript, and here's how to have it in a react project in case you don't know"

2021-03-30 19:42 UTC, merged